// packages/react/src/views/landing/Landing.tsx
import React, { Fragment, useEffect, useState } from 'react';
import Header from '../../components/header/header';
import Avatar from '../../components/avatar/avatar';
import { landingPageConfig } from './landing.config';
import { imageSources } from '../../constants/views/Landing';

import { AvatarTypes } from '../../constants/components/avatar';
import { NavbarModes } from '../../constants/components/header';

import './_landing.scss';

const Landing = () => {
  const [isDarkMode, updateMode] = useState<boolean>(true);
  const getImageSource = (): string =>
    isDarkMode ? imageSources.dark : imageSources.light;

  const customEventHandler = () => {
    alert('clicked');
  };

  return (
    <div className="app-landing">
      <h1>React Application utilizing Header Component</h1>
      {landingPageConfig?.options?.map(
        ({ name, config, hasCustomStyling, hasSlot }, index) => (
          <div
            key={index}
            className={`app-landing-variant ${
              hasCustomStyling ? 'app-landing-variant-custom' : ''
            }`}
          >
            <h2>{name}</h2>
            <header className="app-header">
              <Header
                options={
                  name === 'With Right Slot'
                    ? {
                        ...config,
                        mode: isDarkMode ? NavbarModes.Dark : NavbarModes.Light,
                      }
                    : { ...config }
                }
                hasSlot={hasSlot}
                on-button-click={customEventHandler}
              >
                <Avatar
                  type={AvatarTypes.Image}
                  imageAlt="Theme Icon"
                  source={getImageSource()}
                  handleClick={() => updateMode(!isDarkMode)}
                />
              </Header>
            </header>
          </div>
        )
      )}
    </div>
  );
};

export default Landing;

// packages/vue/src/views/Landing.vue
<script lang="ts">
import { defineComponent } from 'vue';
import HeaderComponent from '@/components/header/header.vue';
import AvatarComponent from '@/components/avatar/avatar.vue';
import { landingPageConfig } from '@/constants/views/landing.config';

import { AvatarTypes } from '@/constants/components/avatar';
import { NavbarModes } from '@/constants/components/header';
import { imageSources } from '@/constants/views/landing';

export default defineComponent({
  name: 'LandingVue',
  components: {
    HeaderComponent,
    AvatarComponent,
  },
  data: () => ({
    landingPageConfig,
    isDarkMode: true,
    navModes: NavbarModes,
    avatarTypes: AvatarTypes,
  }),
  computed: {
    imageSource() {
      return this.isDarkMode ? imageSources.dark : imageSources.light;
    },
  },
  methods: {
    toggleMode() {
      this.isDarkMode = !this.isDarkMode;
    },
    checkBtnClick() {
      alert('clicked');
    },
  },
});
</script>
<template>
  <div class="app-landing">
    <h1>Vue Application utilizing Header Component</h1>
    <div
      v-for="(
        { name, config, hasCustomStyling, hasSlot }, index
      ) in landingPageConfig?.options"
      :key="index"
      :class="`app-landing-variant ${
        hasCustomStyling ? 'app-landing-variant-custom' : ''
      }`"
    >
      <h2>{{ name }}</h2>
      <header class="header">
        <HeaderComponent
          :navOptions="
            name === 'With Right Slot'
              ? {
                  ...config,
                  mode: isDarkMode ? navModes.Dark : navModes.Light,
                }
              : { ...config }
          "
          :hasSlot="hasSlot"
          :slotName="config?.topRightSlot?.slotName"
          @button-click="checkBtnClick"
        >
          <template #header>
            <AvatarComponent
              :type="avatarTypes.Image"
              :source="imageSource"
              @click="toggleMode"
            />
          </template>
        </HeaderComponent>
      </header>
    </div>
  </div>
</template>
