// packages/react/src/components/header/header.tsx
import React, { ReactElement } from 'react';
import reactifyWc from 'reactify-wc';
import '../../third-party/index';
import { NavBarOptions } from '../../types/third-party/header';

interface HeaderProps {
  options: NavBarOptions;
  children?: ReactElement;
  hasSlot?: boolean;
}

const HeaderCL = reactifyWc<{ navOptions: NavBarOptions }>('header-component');

const Header = ({
  options,
  children = <></>,
  hasSlot = false,
  ...props
}: HeaderProps) => {
  return (
    <HeaderCL navOptions={options} {...props}>
      {hasSlot && <div slot={options?.topRightSlot?.slotName}>{children}</div>}
    </HeaderCL>
  );
};

export default Header;

// packages/vue/src/components/header/header.vue
<script lang="ts">
import { defineComponent } from 'vue';
import '@/third-party/index';

export default defineComponent({
  name: 'HeaderElement',
  props: {
    navOptions: {
      type: Object,
      default: null,
    },
    hasSlot: {
      type: Boolean,
      default: false,
    },
    slotName: {
      type: String,
      default: '',
    },
  },
});
</script>

<template>
  <header-component :navOptions="navOptions">
    <!-- eslint-disable vue/no-deprecated-slot-attribute !-->
    <div v-if="hasSlot" :slot="slotName">
      <slot name="header" />
    </div>
  </header-component>
</template>
