// packages/react/src/components/add-todo/addTodo.tsx
import React, { FormEvent } from 'react';
import CardComponent from '../card/card';
import InputBar from '../input-bar/input';
import './_add-todo.scss';

const inputLabel = 'Add Todo Item';

interface AddTodoProps {
  handleInput: (value: string) => void;
  flush?: boolean;
  handleSubmit: (event: FormEvent) => void;
}

const AddTodo = ({
  handleInput,
  flush = false,
  handleSubmit,
}: AddTodoProps) => (
  <div className="d-flex align-items-center justify-content-center app-add-todo-container">
    <CardComponent>
      <form onSubmit={handleSubmit} autoComplete="off">
        <InputBar
          inputLabel={inputLabel}
          handleInput={handleInput}
          flush={flush}
        />
      </form>
    </CardComponent>
  </div>
);

export default AddTodo;

// packages/vue/src/components/add-todo/addTodo.vue
<script lang="ts">
import { defineComponent } from 'vue';
import CardComponent from '@/components/card/card.vue';
import InputComponent from '@/components/input-bar/input.vue';
export default defineComponent({
  name: 'AddTodo',
  components: {
    CardComponent,
    InputComponent,
  },
  data: () => ({
    cardHeading: 'Add Todo Item',
  }),
  props: {
    addTodo: {
      type: Function,
    },
    flush: {
      type: Boolean,
    },
  },
});
</script>

<template>
  <div
    class="d-flex align-items-center justify-content-center app-add-todo-container"
  >
    <CardComponent>
      <template #cardContent>
        <InputComponent
          :inputLabel="cardHeading"
          :handleInput="addTodo"
          :flush="flush"
        />
      </template>
    </CardComponent>
  </div>
</template>
