// packages/react/src/components/input-bar/input.tsx
import React, {
  ChangeEvent,
  forwardRef,
  KeyboardEvent,
  useEffect,
  useState,
} from 'react';
import './_input.scss';

interface InputBarProps {
  inputLabel?: string;
  handleInput?: (value: string) => void;
  flush?: boolean;
}

const InputBar = forwardRef<HTMLInputElement, InputBarProps>(
  ({ inputLabel, handleInput, flush = false }: InputBarProps, ref) => {
    const [inputValue, updateInputValue] = useState<string>('');

    useEffect(() => {
      if (inputValue?.trim()) {
        handleInput?.(inputValue);
      }
    }, [inputValue, handleInput]);

    useEffect(() => {
      if (flush) {
        updateInputValue('');
      }
    }, [flush]);
    return (
      <div className="app-input-bar">
        <label htmlFor="inputBar">{inputLabel}</label>
        <input
          id="inputBar"
          onChange={(event: ChangeEvent) => {
            const target = event.target as HTMLInputElement;
            updateInputValue(target?.value);
          }}
          value={inputValue}
          ref={ref}
        />
      </div>
    );
  }
);

InputBar.displayName = 'InputBar';

export default InputBar;

// packages/vue/src/components/input-bar/input.vue
<!-- eslint-disable @typescript-eslint/no-empty-function -->
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'InputComponent',
  data: () => ({
    inputValue: '',
  }),
  props: {
    inputLabel: {
      type: String,
      default: '',
    },
    handleInput: {
      type: Function,
      default: null,
    },
    flush: {
      type: Boolean,
    },
  },
  methods: {
    handleInputChange(event: KeyboardEvent) {
      this.handleInput(event, this.inputValue);
    },
  },
  watch: {
    flush(oldVal) {
      if (oldVal) {
        this.inputValue = '';
      }
    },
  },
});
</script>

<template>
  <div class="app-input-bar">
    <label for="inputBar">{{ inputLabel }} </label>
    <input
      v-model="inputValue"
      id="inputBar"
      @keyup="handleInputChange"
      autocomplete="off"
    />
  </div>
</template>
